### ISSUE TITLE
Where are the artificats?

### ISSUE THREAD

**Issue by AssafKatz3** [vmware-ibm-jil/vcd_toolkit_for_openshift#1]
Hi,
I am trying to find out how to install OpenShift on VCD and found this repository but the read me contains reference to artifacts that aren't here:

> This repository contains artifacts to create OCP clusters on vCD

Thanks

**Comment by tseelbach** [comment]
Hi, same question.  Especially where is vcd_toolkit_for_openshift4.tar which contains the setup scripts

**Comment by tseelbach** [comment]
the scripts that drive the installation are all published now.  And the needed images are published in the IBM Cloud VMWare Solution Shared public catalog.   
Detailed instructions are in the /doc directory, and  linked from the overall README.md
