### ISSUE TITLE
vmware-airgap: documentation: Install VCD Toolkit

### ISSUE THREAD

**Issue by ianbaldwin2** [vmware-ibm-jil/vcd_toolkit_for_openshift#10]
https://github.com/vmware-ibm-jil/vcd_toolkit_for_openshift/blob/master/doc/ibm-cloud-vss.md#install-vcd-toolkit

Not clear on which repo this is referring to

```
Install VCD Toolkit
clone this repo
cp -r <this repo>/src/ /usr/local/openshift/
```

**Comment by tseelbach** [comment]
fixed in the doc
