### ISSUE TITLE
add support for OpenShift 4.6

### ISSUE THREAD

**Issue by tseelbach** [vmware-ibm-jil/vcd_toolkit_for_openshift#12]
- download/use ocp 4.6 installer
- create coreos 4.6 templates
- ensure that the ignition creation proces and install process still works

There are more and different install options in 4.6.   Hopefully the approach taken currently for ignition creation and install will still work  and we don't need to make major changes.  TBD

**Comment by Sher-Chowdhury** [comment]
By "coreos 4.6 templates" do you mean "rhcos OpenShift 4.6.8" vApp Template? If so then it looks like that now exists in the public catalog:

![image](https://user-images.githubusercontent.com/11390994/105834382-4f14f600-5fc2-11eb-9c49-22a264ecb284.png)

**Comment by slipsibm** [comment]
I suspect that just downloading the 4.6 installer and using the image may not work due to the way the IP stack is handled in 4.6 but have never tried it. If you wait a few more days, I've been working on an installer that works for 4.6. Just shaking the bugs out.

**Comment by c1505** [comment]
@slipsibm Any estimate for when this could work for 4.6 ?

**Comment by tseelbach** [comment]
We provide support for OpenShift on VCD here:  https://github.com/ibm-cloud-architecture/terraform-openshift4-vcd

We have no plans to add OCP 4.6 support in this repo, due to the benefits of the scripting in terraform-openshift4-vcd  such as:
- Supports variable number of workers. VCD toolkit hardcoded the worker count and related LoadBalancer configuration.
- Automatic approval of outstanding CSR's. No more manual step.
- Less manual steps overall. Does not require multiple steps of running scripts, then terraform then more scripts. Just set variables, run terraform, then start VM's.
