### ISSUE TITLE
vmware-airgap: documentation:  Inbound config to OCP Console

### ISSUE THREAD

**Issue by ianbaldwin2** [vmware-ibm-jil/vcd_toolkit_for_openshift#7]
https://github.com/vmware-ibm-jil/vcd_toolkit_for_openshift/blob/master/doc/ibm-cloud-vss.md#inbound-config-to-ocp-console

When configuring NAT. Translated Source IP/Range: IP of Load Balancer is missing an example of the IP to use.

**Comment by tseelbach** [comment]
Fixed here: https://github.com/ibm-cloud-architecture/terraform-openshift4-vcd#inbound-config-to-ocp-console

Won't fix in vcd_toolkit_for_openshift since we are providing OpenShift 4.6+ support over there in terraform-openshift4-vcd
