### ISSUE TITLE
vmware-airgap: documentation: Install preReqs of the Terraform and SimpleHTTP server

### ISSUE THREAD

**Issue by ianbaldwin2** [vmware-ibm-jil/vcd_toolkit_for_openshift#8]
https://github.com/vmware-ibm-jil/vcd_toolkit_for_openshift/blob/master/doc/ibm-cloud-vss.md#install-prereqs-of-the-terraform--and-simplehttp-server

When running yum install

`yum install uzip` should be `yum install unzip`

I had to add 8.8.8.8 to `/etc/resolv.conf` to download
- wget https://releases.hashicorp.com/terraform/0.12.17/terraform_0.12.17_linux_amd64.zip

Not clear on what needs to be done here
```
You also need the Terraform VMware vCloud Director Provider. TODO I can't find the download link :) Source is here
```

**Comment by tseelbach** [comment]
- fixed "yum install uzip" - 

- Terraform vCloud Director Provider is now installed automatically.  Scripts and doc updated

**Comment by tseelbach** [comment]
the /etc/resolv.conf addition of public DNS may still be a problem until after dnsmasq is configured and restarted.  after that bastion should resolve public names

**Comment by tseelbach** [comment]
The /etc/resolv.conf addition of public DNS doesn't appear to be a problem in https://github.com/ibm-cloud-architecture/terraform-openshift4-vcd.   Since that is where we are concentrated for OpenShift 4.6 and beyond, i'm closing this - Won't fix.
